version: '3'

services:
  phoenix:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db

  chall19:
    build:
      context: .
      dockerfile: Dockerfile.chall19
    ports:
      - '4045:8000'
    depends_on:
      - phoenix

  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  

volumes:
  pgdata:
